# This workflow will build platform-specific distributable that can be run without python installed and
# makes it available under Github releases
name: Build Python Distributable

# Trigger the create release workflow
on:
  workflow_run:
    workflows: [Upload Python Package]
    types: 
      - completed

permissions:
  contents: read

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build distributable
      run: pyinstaller sipper.spec
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bottle-sipper-linux-x64
        path: dist/*

  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build distributable
        run: pyinstaller sipper.spec
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bottle-sipper-windows-x64
          path: dist/*

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build distributable
        run: pyinstaller sipper.spec
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bottle-sipper-macos-x64
          path: dist/*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-x64, build-windows-x64, build-macos-x64]
    steps:
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v2
        with:
          name: bottle-sipper-linux-x64
          path: dist/dist-linux
      - name: Rename Linux Artifact Files
        run: |
          cd dist/dist-linux
          suffix="linux-x64"
          for file in *; do
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename_without_extension="${filename%.*}"
            new_filename="${filename_without_extension}-${suffix}.${extension}"
            mv "$file" "$new_filename"
          done

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v2
        with:
          name: bottle-sipper-windows-x64
          path: dist/dist-windows
      - name: Rename Windows Artifact Files
        run: |
          cd dist/dist-windows
          suffix="windows-x64"
          for file in *; do
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename_without_extension="${filename%.*}"
            new_filename="${filename_without_extension}-${suffix}.${extension}"
            mv "$file" "$new_filename"
          done

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v2
        with:
          name: bottle-sipper-macos-x64
          path: dist/dist-macos
      - name: Rename macOS Artifact Files
        run: |
          cd dist/dist-macos
          suffix="macos-x64"
          for file in *; do
            filename=$(basename -- "$file")
            extension="${filename##*.}"
            filename_without_extension="${filename%.*}"
            new_filename="${filename_without_extension}-${suffix}.${extension}"
            mv "$file" "$new_filename"
          done

      - name: Calculate Checksums
        run: |
          cd ${{ github.workspace }}
          cd dist
          md5sum * > MD5SUMS
          sha1sum * > SHA1SUMS
          sha256sum * > SHA256SUMS
          sha512sum * > SHA512SUMS

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            dist/dist-linux/**
            dist/dist-windows/**
            dist/dist-macos/**

      - name: Set Release URL as Output
        id: set_release_url
        run: echo "RELEASE_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Display Release URL
        run: |
          echo "Release URL: $RELEASE_URL"
